// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// FFI 배선 확인용 자리표시자 함수 — 실제 기능이 추가되면 지운다.
String greet({required String name}) =>
    RustLib.instance.api.crateApiGreet(name: name);
