// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'api/capability.dart';
import 'api/dashboard.dart';
import 'api/i18n.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  SessionStateDto dco_decode_box_autoadd_session_state_dto(dynamic raw);

  @protected
  CapabilityDto dco_decode_capability_dto(dynamic raw);

  @protected
  EventSourceDto dco_decode_event_source_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SessionOrderKeyDto> dco_decode_list_session_order_key_dto(dynamic raw);

  @protected
  LocaleDto dco_decode_locale_dto(dynamic raw);

  @protected
  SessionStateDto? dco_decode_opt_box_autoadd_session_state_dto(dynamic raw);

  @protected
  SessionOrderKeyDto dco_decode_session_order_key_dto(dynamic raw);

  @protected
  SessionStateDto dco_decode_session_state_dto(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UnsupportedReasonDto dco_decode_unsupported_reason_dto(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  SessionStateDto sse_decode_box_autoadd_session_state_dto(
    SseDeserializer deserializer,
  );

  @protected
  CapabilityDto sse_decode_capability_dto(SseDeserializer deserializer);

  @protected
  EventSourceDto sse_decode_event_source_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SessionOrderKeyDto> sse_decode_list_session_order_key_dto(
    SseDeserializer deserializer,
  );

  @protected
  LocaleDto sse_decode_locale_dto(SseDeserializer deserializer);

  @protected
  SessionStateDto? sse_decode_opt_box_autoadd_session_state_dto(
    SseDeserializer deserializer,
  );

  @protected
  SessionOrderKeyDto sse_decode_session_order_key_dto(
    SseDeserializer deserializer,
  );

  @protected
  SessionStateDto sse_decode_session_state_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UnsupportedReasonDto sse_decode_unsupported_reason_dto(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_session_state_dto(
    SessionStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_capability_dto(CapabilityDto self, SseSerializer serializer);

  @protected
  void sse_encode_event_source_dto(
    EventSourceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_session_order_key_dto(
    List<SessionOrderKeyDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_locale_dto(LocaleDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_session_state_dto(
    SessionStateDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_order_key_dto(
    SessionOrderKeyDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_state_dto(
    SessionStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_unsupported_reason_dto(
    UnsupportedReasonDto self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
