// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api/capability.dart';
import 'api/dashboard.dart';
import 'api/i18n.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1012384457;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'my_dashboard_frb',
        ioDirectory: '../app-frb/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  CapabilityDto crateApiCapabilityCapabilityFor({
    required String capabilityId,
    required bool windowControlReady,
    required bool globalHotkeyReady,
    required bool notifyLocalReady,
  });

  String crateApiGreet({required String name});

  bool crateApiDashboardIsSessionStale({
    required PlatformInt64 now,
    required PlatformInt64 updatedAt,
    required PlatformInt64 staleMs,
  });

  List<SessionOrderKeyDto> crateApiDashboardSortSessionOrder({
    required List<SessionOrderKeyDto> sessions,
  });

  SessionStateDto? crateApiDashboardStateForEvent({
    required EventSourceDto source,
    required String event,
  });

  String crateApiDashboardStateLabelKey({required SessionStateDto state});

  String crateApiI18NTranslate({
    required String key,
    required LocaleDto locale,
  });

  String crateApiI18NTranslateArgs({
    required String key,
    required LocaleDto locale,
    required List<String> argKeys,
    required List<String> argVals,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  CapabilityDto crateApiCapabilityCapabilityFor({
    required String capabilityId,
    required bool windowControlReady,
    required bool globalHotkeyReady,
    required bool notifyLocalReady,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(capabilityId, serializer);
          sse_encode_bool(windowControlReady, serializer);
          sse_encode_bool(globalHotkeyReady, serializer);
          sse_encode_bool(notifyLocalReady, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_capability_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCapabilityCapabilityForConstMeta,
        argValues: [
          capabilityId,
          windowControlReady,
          globalHotkeyReady,
          notifyLocalReady,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCapabilityCapabilityForConstMeta =>
      const TaskConstMeta(
        debugName: "capability_for",
        argNames: [
          "capabilityId",
          "windowControlReady",
          "globalHotkeyReady",
          "notifyLocalReady",
        ],
      );

  @override
  String crateApiGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  bool crateApiDashboardIsSessionStale({
    required PlatformInt64 now,
    required PlatformInt64 updatedAt,
    required PlatformInt64 staleMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(now, serializer);
          sse_encode_i_64(updatedAt, serializer);
          sse_encode_i_64(staleMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDashboardIsSessionStaleConstMeta,
        argValues: [now, updatedAt, staleMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDashboardIsSessionStaleConstMeta =>
      const TaskConstMeta(
        debugName: "is_session_stale",
        argNames: ["now", "updatedAt", "staleMs"],
      );

  @override
  List<SessionOrderKeyDto> crateApiDashboardSortSessionOrder({
    required List<SessionOrderKeyDto> sessions,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_session_order_key_dto(sessions, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_session_order_key_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDashboardSortSessionOrderConstMeta,
        argValues: [sessions],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDashboardSortSessionOrderConstMeta =>
      const TaskConstMeta(
        debugName: "sort_session_order",
        argNames: ["sessions"],
      );

  @override
  SessionStateDto? crateApiDashboardStateForEvent({
    required EventSourceDto source,
    required String event,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_event_source_dto(source, serializer);
          sse_encode_String(event, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_session_state_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDashboardStateForEventConstMeta,
        argValues: [source, event],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDashboardStateForEventConstMeta =>
      const TaskConstMeta(
        debugName: "state_for_event",
        argNames: ["source", "event"],
      );

  @override
  String crateApiDashboardStateLabelKey({required SessionStateDto state}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_session_state_dto(state, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDashboardStateLabelKeyConstMeta,
        argValues: [state],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDashboardStateLabelKeyConstMeta =>
      const TaskConstMeta(debugName: "state_label_key", argNames: ["state"]);

  @override
  String crateApiI18NTranslate({
    required String key,
    required LocaleDto locale,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          sse_encode_locale_dto(locale, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiI18NTranslateConstMeta,
        argValues: [key, locale],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiI18NTranslateConstMeta =>
      const TaskConstMeta(debugName: "translate", argNames: ["key", "locale"]);

  @override
  String crateApiI18NTranslateArgs({
    required String key,
    required LocaleDto locale,
    required List<String> argKeys,
    required List<String> argVals,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          sse_encode_locale_dto(locale, serializer);
          sse_encode_list_String(argKeys, serializer);
          sse_encode_list_String(argVals, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiI18NTranslateArgsConstMeta,
        argValues: [key, locale, argKeys, argVals],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiI18NTranslateArgsConstMeta => const TaskConstMeta(
    debugName: "translate_args",
    argNames: ["key", "locale", "argKeys", "argVals"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  SessionStateDto dco_decode_box_autoadd_session_state_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_session_state_dto(raw);
  }

  @protected
  CapabilityDto dco_decode_capability_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CapabilityDto_Supported();
      case 1:
        return CapabilityDto_Unsupported(
          reason: dco_decode_unsupported_reason_dto(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  EventSourceDto dco_decode_event_source_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EventSourceDto.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SessionOrderKeyDto> dco_decode_list_session_order_key_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_session_order_key_dto)
        .toList();
  }

  @protected
  LocaleDto dco_decode_locale_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LocaleDto.values[raw as int];
  }

  @protected
  SessionStateDto? dco_decode_opt_box_autoadd_session_state_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_session_state_dto(raw);
  }

  @protected
  SessionOrderKeyDto dco_decode_session_order_key_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SessionOrderKeyDto(
      state: dco_decode_session_state_dto(arr[0]),
      updatedAt: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  SessionStateDto dco_decode_session_state_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SessionStateDto.values[raw as int];
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UnsupportedReasonDto dco_decode_unsupported_reason_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UnsupportedReasonDto.values[raw as int];
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  SessionStateDto sse_decode_box_autoadd_session_state_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_session_state_dto(deserializer));
  }

  @protected
  CapabilityDto sse_decode_capability_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return CapabilityDto_Supported();
      case 1:
        var var_reason = sse_decode_unsupported_reason_dto(deserializer);
        return CapabilityDto_Unsupported(reason: var_reason);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  EventSourceDto sse_decode_event_source_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return EventSourceDto.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SessionOrderKeyDto> sse_decode_list_session_order_key_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SessionOrderKeyDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_session_order_key_dto(deserializer));
    }
    return ans_;
  }

  @protected
  LocaleDto sse_decode_locale_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return LocaleDto.values[inner];
  }

  @protected
  SessionStateDto? sse_decode_opt_box_autoadd_session_state_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_session_state_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SessionOrderKeyDto sse_decode_session_order_key_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_state = sse_decode_session_state_dto(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    return SessionOrderKeyDto(state: var_state, updatedAt: var_updatedAt);
  }

  @protected
  SessionStateDto sse_decode_session_state_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SessionStateDto.values[inner];
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UnsupportedReasonDto sse_decode_unsupported_reason_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return UnsupportedReasonDto.values[inner];
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_session_state_dto(
    SessionStateDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_session_state_dto(self, serializer);
  }

  @protected
  void sse_encode_capability_dto(CapabilityDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CapabilityDto_Supported():
        sse_encode_i_32(0, serializer);
      case CapabilityDto_Unsupported(reason: final reason):
        sse_encode_i_32(1, serializer);
        sse_encode_unsupported_reason_dto(reason, serializer);
    }
  }

  @protected
  void sse_encode_event_source_dto(
    EventSourceDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_session_order_key_dto(
    List<SessionOrderKeyDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_session_order_key_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_locale_dto(LocaleDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_session_state_dto(
    SessionStateDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_session_state_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_session_order_key_dto(
    SessionOrderKeyDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_session_state_dto(self.state, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_session_state_dto(
    SessionStateDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_unsupported_reason_dto(
    UnsupportedReasonDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }
}
