// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'capability.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `from`, `from`

/// 현재 런타임에서 `capability_id` 기능을 쓸 수 있는지 조회한다.
///
/// 동기 호출(`frb(sync)`)이라 Dart 쪽에서 `Future` 없이 위젯 `build`
/// 안에서 바로 부를 수 있다 — 조회가 정적 테이블 룩업 하나뿐이라 비동기
/// 왕복을 물릴 이유가 없다.
CapabilityDto capabilityFor({
  required String capabilityId,
  required bool windowControlReady,
  required bool globalHotkeyReady,
  required bool notifyLocalReady,
}) => RustLib.instance.api.crateApiCapabilityCapabilityFor(
  capabilityId: capabilityId,
  windowControlReady: windowControlReady,
  globalHotkeyReady: globalHotkeyReady,
  notifyLocalReady: notifyLocalReady,
);

@freezed
sealed class CapabilityDto with _$CapabilityDto {
  const CapabilityDto._();

  /// 이 런타임에서 쓸 수 있다.
  const factory CapabilityDto.supported() = CapabilityDto_Supported;

  /// 쓸 수 없다.
  const factory CapabilityDto.unsupported({
    /// 왜 못 쓰는지.
    required UnsupportedReasonDto reason,
  }) = CapabilityDto_Unsupported;
}

/// [`app_core::capability::UnsupportedReason`]의 브리지 표현.
enum UnsupportedReasonDto {
  /// wasm(web/PWA) 런타임이라 네이티브 OS 호스트가 없다.
  noWasmHost,

  /// 네이티브(데스크톱/모바일) 런타임이라 브라우저 호스트가 없다 —
  /// [`app_core::capability::Host::Web`] 기능을 네이티브에서 물었을 때다.
  noBrowserHost,

  /// 앱의 플러그인 실행 경로가 없거나 실제 동작이 아직 확인되지 않았다.
  notConfigured,

  /// 카탈로그에 없는 capability id.
  unknownCapability,
}
