// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`

/// `(source, event)`가 어느 상태로 이어지는지 조회한다. 표에 없는 조합은
/// `None` — 상태를 바꾸지 않는다는 뜻이다.
SessionStateDto? stateForEvent({
  required EventSourceDto source,
  required String event,
}) => RustLib.instance.api.crateApiDashboardStateForEvent(
  source: source,
  event: event,
);

/// 상태 → i18n 키(`translate`/`translate_args`와 함께 쓴다).
String stateLabelKey({required SessionStateDto state}) =>
    RustLib.instance.api.crateApiDashboardStateLabelKey(state: state);

/// `updated_at`부터 `now`까지 `stale_ms`를 초과해 지났는지 조회한다(전부
/// epoch ms).
bool isSessionStale({
  required PlatformInt64 now,
  required PlatformInt64 updatedAt,
  required PlatformInt64 staleMs,
}) => RustLib.instance.api.crateApiDashboardIsSessionStale(
  now: now,
  updatedAt: updatedAt,
  staleMs: staleMs,
);

/// `sessions`를 "alert 우선 → `updated_at` 내림차순"으로 안정 정렬해
/// 돌려준다.
List<SessionOrderKeyDto> sortSessionOrder({
  required List<SessionOrderKeyDto> sessions,
}) =>
    RustLib.instance.api.crateApiDashboardSortSessionOrder(sessions: sessions);

/// [`app_core::dashboard::EventSource`]의 브리지 표현.
enum EventSourceDto {
  /// Claude Code.
  claudeCode,

  /// Codex CLI.
  codex,

  /// Devin CLI.
  devin,

  /// 임의의 스크립트·CI가 직접 상태를 신고하는 통로.
  generic,
}

/// 화면 목록 정렬에 필요한 최소 필드의 브리지 표현.
class SessionOrderKeyDto {
  /// 현재 세션 상태.
  final SessionStateDto state;

  /// 마지막 갱신 시각(epoch ms).
  final PlatformInt64 updatedAt;

  const SessionOrderKeyDto({required this.state, required this.updatedAt});

  @override
  int get hashCode => state.hashCode ^ updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionOrderKeyDto &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          updatedAt == other.updatedAt;
}

/// [`app_core::dashboard::SessionState`]의 브리지 표현.
enum SessionStateDto {
  /// 세션이 열려 있고 사람의 입력을 기다린다.
  idle,

  /// 에이전트가 실행 중이다.
  working,

  /// 질문·승인 대기.
  waitingInput,

  /// 턴 실행을 마쳤다.
  done,

  /// 세션이 끝났다.
  ended,

  /// working이었는데 신호가 끊겼다(서버가 만드는 derived 상태).
  stalled,
}
