// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `from`

/// `key`를 `locale`로 번역한다.
///
/// 카탈로그에 없는 키는 예외를 던지지 않고 눈에 띄는 표식(`???`)으로
/// 돌아온다 — 폴백 규칙은 [`app_core::i18n::t`] 문서 참고.
String translate({required String key, required LocaleDto locale}) =>
    RustLib.instance.api.crateApiI18NTranslate(key: key, locale: locale);

/// `key`를 번역한 뒤 `{name}` 자리표시자를 채운다.
///
/// 인자를 `Map` 대신 평행한 두 리스트(`arg_keys`/`arg_vals`)로 받는 이유:
/// 브리지 경계에서 맵 타입을 주고받으면 Dart↔Rust 양쪽에 변환 코드가
/// 생기는데, 이 호출의 인자 수는 한 자릿수라 그 비용이 이득보다 크다.
/// Dart 쪽 어댑터(`t.dart`)가 호출부의 `Map`을 이 두 리스트로 편다.
///
/// 길이가 다르면 짧은 쪽까지만 짝지어 쓴다 — 남는 항목은 무시되고, 채우지
/// 못한 자리표시자는 `{name}` 그대로 화면에 남아 누락이 드러난다.
String translateArgs({
  required String key,
  required LocaleDto locale,
  required List<String> argKeys,
  required List<String> argVals,
}) => RustLib.instance.api.crateApiI18NTranslateArgs(
  key: key,
  locale: locale,
  argKeys: argKeys,
  argVals: argVals,
);

/// [`app_core::i18n::Locale`]의 브리지 표현.
enum LocaleDto {
  /// English.
  en,

  /// 한국어.
  ko,
}
